/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DrivingExperience = IDL.Variant({
  'threePlusYears' : IDL.Null,
  'zeroToOneYear' : IDL.Null,
  'oneToThreeYears' : IDL.Null,
});
export const Location = IDL.Variant({
  'ghatkopar' : IDL.Null,
  'other' : IDL.Text,
  'kurla' : IDL.Null,
});
export const Time = IDL.Int;
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'drivingLicenseNumber' : IDL.Text,
  'fullName' : IDL.Text,
  'experience' : DrivingExperience,
  'phoneNumber' : IDL.Text,
  'location' : Location,
  'createdAtNanos' : Time,
});

export const idlService = IDL.Service({
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getTotalApplications' : IDL.Func([], [IDL.Nat], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, Location, IDL.Text, DrivingExperience],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DrivingExperience = IDL.Variant({
    'threePlusYears' : IDL.Null,
    'zeroToOneYear' : IDL.Null,
    'oneToThreeYears' : IDL.Null,
  });
  const Location = IDL.Variant({
    'ghatkopar' : IDL.Null,
    'other' : IDL.Text,
    'kurla' : IDL.Null,
  });
  const Time = IDL.Int;
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'drivingLicenseNumber' : IDL.Text,
    'fullName' : IDL.Text,
    'experience' : DrivingExperience,
    'phoneNumber' : IDL.Text,
    'location' : Location,
    'createdAtNanos' : Time,
  });
  
  return IDL.Service({
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getTotalApplications' : IDL.Func([], [IDL.Nat], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, Location, IDL.Text, DrivingExperience],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };