/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Location = {
    __kind__: "ghatkopar";
    ghatkopar: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "kurla";
    kurla: null;
};
export type Time = bigint;
export interface Application {
    id: bigint;
    drivingLicenseNumber: string;
    fullName: string;
    experience: DrivingExperience;
    phoneNumber: string;
    location: Location;
    createdAtNanos: Time;
}
export enum DrivingExperience {
    threePlusYears = "threePlusYears",
    zeroToOneYear = "zeroToOneYear",
    oneToThreeYears = "oneToThreeYears"
}
export interface backendInterface {
    getAllApplications(): Promise<Array<Application>>;
    getTotalApplications(): Promise<bigint>;
    submitApplication(fullName: string, phoneNumber: string, location: Location, drivingLicenseNumber: string, experience: DrivingExperience): Promise<void>;
}
import type { Application as _Application, DrivingExperience as _DrivingExperience, Location as _Location, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalApplications(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalApplications();
            return result;
        }
    }
    async submitApplication(arg0: string, arg1: string, arg2: Location, arg3: string, arg4: DrivingExperience): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1, to_candid_Location_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_DrivingExperience_n10(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1, to_candid_Location_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_DrivingExperience_n10(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_Application_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DrivingExperience_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrivingExperience): DrivingExperience {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    drivingLicenseNumber: string;
    fullName: string;
    experience: _DrivingExperience;
    phoneNumber: string;
    location: _Location;
    createdAtNanos: _Time;
}): {
    id: bigint;
    drivingLicenseNumber: string;
    fullName: string;
    experience: DrivingExperience;
    phoneNumber: string;
    location: Location;
    createdAtNanos: Time;
} {
    return {
        id: value.id,
        drivingLicenseNumber: value.drivingLicenseNumber,
        fullName: value.fullName,
        experience: from_candid_DrivingExperience_n4(_uploadFile, _downloadFile, value.experience),
        phoneNumber: value.phoneNumber,
        location: from_candid_Location_n6(_uploadFile, _downloadFile, value.location),
        createdAtNanos: value.createdAtNanos
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threePlusYears: null;
} | {
    zeroToOneYear: null;
} | {
    oneToThreeYears: null;
}): DrivingExperience {
    return "threePlusYears" in value ? DrivingExperience.threePlusYears : "zeroToOneYear" in value ? DrivingExperience.zeroToOneYear : "oneToThreeYears" in value ? DrivingExperience.oneToThreeYears : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ghatkopar: null;
} | {
    other: string;
} | {
    kurla: null;
}): {
    __kind__: "ghatkopar";
    ghatkopar: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "kurla";
    kurla: null;
} {
    return "ghatkopar" in value ? {
        __kind__: "ghatkopar",
        ghatkopar: value.ghatkopar
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "kurla" in value ? {
        __kind__: "kurla",
        kurla: value.kurla
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n2(_uploadFile, _downloadFile, x));
}
function to_candid_DrivingExperience_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrivingExperience): _DrivingExperience {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Location_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location): _Location {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrivingExperience): {
    threePlusYears: null;
} | {
    zeroToOneYear: null;
} | {
    oneToThreeYears: null;
} {
    return value == DrivingExperience.threePlusYears ? {
        threePlusYears: null
    } : value == DrivingExperience.zeroToOneYear ? {
        zeroToOneYear: null
    } : value == DrivingExperience.oneToThreeYears ? {
        oneToThreeYears: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "ghatkopar";
    ghatkopar: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "kurla";
    kurla: null;
}): {
    ghatkopar: null;
} | {
    other: string;
} | {
    kurla: null;
} {
    return value.__kind__ === "ghatkopar" ? {
        ghatkopar: value.ghatkopar
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "kurla" ? {
        kurla: value.kurla
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
